---
title: "Basic tests with simulated data"
output: html_notebook
---

This notebook tests that the implemented models can be run on simulated data and roughly recover parameters, the tests are meant to be quick and not really rigorous  

```{r setup}
devtools::load_all()
library(rstan)
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)
library(here)
library(tidyverse)
```

```{r compile_models}
model_dirichlet_multinomial = stan_model(here("stan","dirichlet_multinomial_base.stan"))
model_multinomial = stan_model(here("stan","multinomial.stan"))
model_lognormal_multinomial = stan_model(here("stan","logNormal_multinomial.stan"))
model_nb_multinomial_approx = stan_model(here("stan","nb_multinomial_approx.stan"))
```

# Multinomial

```{r}
G = 5
N = 10
sums = G * 10 + rnbinom(N, mu = G * 50, size = 1) 
data = generate_data_multinomial(G, sums)
fit = sampling(model_multinomial, data = data$observed)
evaluation_summary(fit, data$true)
```

# Neg. binomial multinomial

```{r}
G = 5
N = 10
sums = G * 10 + rnbinom(N, mu = G * 50, size = 1) 
data = generate_data_nb_multinomial(G, sums, lambda_raw_sigma = 2)
fit = sampling(model_nb_multinomial_approx, data = data$observed)
evaluation_summary(fit, data$true)
```


# Dirichlet multinomial - Martin's variant

```{r}
G = 5
sums = c(100,200,300)
lambda_raw_prior = 2 
data = generate_data_dirichlet_multinomial_base(G, sums, lambda_raw_prior)
fit = sampling(model_dirichlet_multinomial, data = data$observed)
evaluation_summary(fit, data$true)
```

# LogNormal Multinomial

```{r}
G = 4
N = 6
sums = G * 10 + rnbinom(N, mu = G * 50, size = 1) 
data = generate_data_lognormal_multinomial(G, sums)
fit = sampling(model_lognormal_multinomial, data = data$observed, control = list(max_treedepth = 12, adapt_delta = 0.9), iter = 500)
evaluation_summary(fit, data$true)
```

```{r}
G = 5
N = 10
sums = G * 10 + rnbinom(N, mu = G * 50, size = 1) 
data = generate_data_lognormal_multinomial(G, sums, is_prior_assymetric = TRUE)
fit = sampling(model_lognormal_multinomial, data = data$observed, control = list(max_treedepth = 12, adapt_delta = 0.9), iter = 500)
evaluation_summary(fit, data$true)
```
