---
title: "Understanding Poisson-Tweedie"
output: html_notebook
---


```{r setup}
library(tweeDEseq)
library(tidyverse)
library(rstan)
library(here)
options(mc.cores = parallel::detectCores())
devtools::load_all()
```

```{r}
dd <- tibble(mu = 10, D = 2) %>% crossing(a = c(-1e20, -10,-0.5,0,0.3,0.5,0.7,0.9)) %>%
  crossing(x = 0:100) %>%
  group_by(mu, D, a) %>%
  mutate(dens = dPT(x, unique(mu), unique(D), unique(a))) %>%
  ungroup() %>%
  mutate(log_dens = log(dens), a_ = factor(a))

dd %>% filter(x < 20) %>% ggplot(aes(x = x, y = dens, color = a_, group = a_)) + geom_line()
dd %>% ggplot(aes(x = x, y = log_dens, color = a_, group = a_)) + geom_line()
```

```{r}

```


$\log(r_i)$ and its derivatives:

$$
\log(r_1) = \log(1-a) + \log(c)  \\
\frac{\partial log(r_1)}{a} = - \frac{1}{1-a} \\
$$
Used in d/da log(r_j+1)
https://www.wolframalpha.com/input/?i=sum+1%2F%28a+%2B+i+-+1%29%2C+i%3D2+to+j

d/da log(p_0)
https://www.wolframalpha.com/input/?i=d%2Fda+b*%28%281-c%29%5Ea+-+1%29+%2F+a

https://www.wolframalpha.com/input/?i=lim+a+-%3E+0+%28b+%28-%281+-+c%29%5Ea+%2B+a+%281+-+c%29%5Ea+log%281+-+c%29+%2B+1%29%29%2Fa%5E2

d/db log(p_0)
https://www.wolframalpha.com/input/?i=d%2Fdb+b*%28%281-c%29%5Ea+-+1%29+%2F+a

https://www.wolframalpha.com/input/?i=lim+a-%3E0+%28%281+-+c%29%5Ea+-+1%29%2Fa


```{r}

includes_in_namespace <- paste0("\n#include \"", here("dev","poisson_tweedie.hpp"), "\"\n")
includes_outside_namespace <- paste0("\n#include \"", here("dev","poisson_tweedie_outside_namespace.hpp"), "\"\n")

stanc_res <- stanc(here("stan","poisson_tweedie_devel.stan"),allow_undefined = TRUE);

# This might be necessary in 
# #I need to put the includes outside of model namespace, hence the hack here
# stanc_res$cppcode <- paste0(includes_outside_namespace, stanc_res$cppcode)
# 
# # And copying from the code of the stan_model function (in rstan.R) as includes are supported there (not in stanc)
# stanc_res$cppcode <- sub("(class[[:space:]]+[A-Za-z_][A-Za-z0-9_]*[[:space:]]*: public prob_grad \\{)",
#                      paste(includes_in_namespace, "\\1"), stanc_res$cppcode)


# HUUUUGE Hack to move things outside namespace
# End and recreate the automatic namespace from expose_stan_functions
tf <- tempfile(fileext = ".stan")
writeLines(stanc_res$model_code, con = tf)
md5 <- paste("user", tools::md5sum(tf), sep = "_")

includes <- paste0(" } \n", includes_outside_namespace, 
                   "\nnamespace ", md5, " {\n",
                   includes_in_namespace
                   )

cat(stanc_res$cppcode, file = here("model.cpp"))
expose_stan_functions(stanc_res, show_compiler_warnings = TRUE, rebuild = TRUE, includes = includes)
# model <- stan_model(here("stan","poisson_tweedie.stan"),allow_undefined = TRUE, includes = includes, verbose = TRUE)
# 
# expose_stan_functions(model, includes = includes, show_compiler_warnings = TRUE)

```

```{r}
compare_to_dpT <- function(x, log_mu, D, a) {
  print(poisson_tweedie_raw_wrapper(x, log_mu, D, a))
  print(sum(log(dPT(x, exp(log_mu), D, a))))
}

compare_to_dpT(c(0:10), -2, 1.1, 0.5)
compare_to_dpT(c(0:2), 3, 10, -0.5)
compare_to_dpT(c(0:10), 1, 1.8, 0)
compare_to_dpT(130, log(100), 1.5, -4)
compare_to_dpT(130, log(100), 1.5, 0.2)
compare_to_dpT(c(0:10), -2, 1.1, 0.5)

finite_difference_da <- function(x, a, b, c) {
  step <- 1e-12
  print((poisson_tweedie_abc_wrapper(x, a + step, b, c) - poisson_tweedie_abc_wrapper(x, a, b, c)) / step)
  print(poisson_tweedie_abc_da_wrapper(x, a, b, c))
  
}

finite_difference_da(0, 0.3, 0.3, 0.5)
finite_difference_da(0, -0.1, 0.3, 0.5)
finite_difference_da(0, -1e-20, 0.3, 0.5)


finite_difference_da(5, 0.3, 0.3, 0.5)
```


```{r}
tibble(a = c(- exp(seq(-40,-1)), 0, exp(seq(-1, -40))), b = 0.3, c = 0.5) %>% rowwise() %>% mutate(lpmf = poisson_tweedie_abc_wrapper(0, a, b, c)) %>% arrange(a) #%>% ggplot(aes(a, lpmf)) + geom_line()
```

```{r}
log1m_exp <- function(a) {
  if(is.nan(a)) {
    NaN
  }
  else if (a >= 0) {
     NaN
  } else if (a > -0.693147) {
     log(-expm1(a))
  } else {
     log1p(-exp(a))
  }  
}

log_diff_exp <- function(x,y) {
  x + log1m_exp(y - x);
}

 
```


```{r}
library(tidyverse)
tibble(a = c(10^(seq(-1, -20))), c = 0.5) %>% rowwise() %>% mutate(orig = ((1.0-c)^a - 1.0) /a, series = log(1-c) + 0.5 * (a * log(1-c)^2) + (a^2 * log(1-c) ^ 3)/ 6)  %>% arrange(a)
```

```{r}
tibble(a = seq(-2, 1, length.out = 201)) %>% crossing(tibble(c = seq(0.4,0.6, length.out = 201))) %>% rowwise() %>% mutate(orig = ((1.0-c)^a - 1.0) /a ) %>% ggplot(aes(x = a, y = c, fill = orig)) + geom_raster() + scale_fill_continuous()
```

```{r}

includes_in_namespace <- paste0("\n#include \"", here("dev","poisson_tweedie.hpp"), "\"\n")
includes_outside_namespace <- paste0("\n#include \"", here("dev","poisson_tweedie_outside_namespace.hpp"), "\"\n")

stanc_res <- stanc(here("stan","poisson_tweedie_devel.stan"),allow_undefined = TRUE);

#I need to put the includes outside of model namespace, hence the hack here
stanc_res$cppcode <- paste0(includes_outside_namespace, stanc_res$cppcode)

# And copying from the code of the stan_model function (in rstan.R) as includes are supported there (not in stanc)
stanc_res$cppcode <- sub("(class[[:space:]]+[A-Za-z_][A-Za-z0-9_]*[[:space:]]*: public prob_grad \\{)",
                     paste(includes_in_namespace, "\\1"), stanc_res$cppcode)

devel_model <- stan_model(stanc_ret = stanc_res)
```

```{r}
mu_prior_logmean <- 4
mu_prior_sigma <- 2
Dm1_prior_logmean <- 1
Dm1_prior_sigma <- 1


mu = rlnorm(1, mu_prior_logmean, mu_prior_sigma)
D = rlnorm(1, Dm1_prior_logmean, Dm1_prior_sigma) + 1
a = runif(1) # - rlnorm(1,1)

# b = (mu * (1 - a)^(1 - a))/((D - 1) * (D - a)^(-a));
# c = (D - 1)/(D - a);

N = 100

data <- list(
  N = N,
  mu_prior_logmean = mu_prior_logmean,
  mu_prior_sigma = mu_prior_sigma,
  Dm1_prior_logmean = Dm1_prior_logmean,
  Dm1_prior_sigma = Dm1_prior_sigma,
  y = rPT(N, mu = mu, D = D, a = a, max = 10 * mu * D)
)

fit <- sampling(devel_model, data = data)
fit                

```


```{r}

generator <- function(N) {
  function() {
    a = runif(1) # - rlnorm(1,1)
    mu_prior_logmean <- 2
    mu_prior_sigma <- 1.5
    Dm1_prior_logmean <- 1
    Dm1_prior_sigma <- 1
    
    
    mu = rlnorm(1, mu_prior_logmean, mu_prior_sigma)
    D = rlnorm(1, Dm1_prior_logmean, Dm1_prior_sigma) + 1

    b = (mu * (1 - a)^(1 - a))/((D - 1) * (D - a)^(-a));
    c = (D - 1)/(D - a);
    list(observed = list(
        N = N,
        mu_prior_logmean = mu_prior_logmean,
        mu_prior_sigma = mu_prior_sigma,
        Dm1_prior_logmean = Dm1_prior_logmean,
        Dm1_prior_sigma = Dm1_prior_sigma,
        y = rPT(N, mu = mu, D = D, a = a, max = 10 * mu * sqrt(D))
        ),
        true = list(a = a, mu = mu, D = D)
    )
  }
}

sbc_res = sbc(devel_model, generator(N = 50), N_steps = 100, cores = 6)
plot_sbc_params(sbc_res$params)
```


```{r}
includes_in_namespace <- paste0("\n#include \"", here("dev","poisson_tweedie.hpp"), "\"\n")
includes_outside_namespace <- paste0("\n#include \"", here("dev","poisson_tweedie_outside_namespace.hpp"), "\"\n")

stanc_res <- stanc(here("stan","poisson_tweedie.stan"),allow_undefined = TRUE);

#I need to put the includes outside of model namespace, hence the hack here
stanc_res$cppcode <- paste0(includes_outside_namespace, stanc_res$cppcode)

# And copying from the code of the stan_model function (in rstan.R) as includes are supported there (not in stanc)
stanc_res$cppcode <- sub("(class[[:space:]]+[A-Za-z_][A-Za-z0-9_]*[[:space:]]*: public prob_grad \\{)",
                     paste(includes_in_namespace, "\\1"), stanc_res$cppcode)

base_model <- stan_model(stanc_ret = stanc_res)
```

```{r}
log_mu <- rnorm(1, 0, 2)
mu = exp(log_mu)
D <- abs(rt(1, df = 3))
a <- rbeta(1, 1, 5);


N = 100

data <- list(
  N = N,
  y = rPT(N, mu = mu, D = D, a = a, max = 10 * max(mu, 2) * max(D, 1)),
  method = 0
)

cat(paste0("Max y = ", max(data$y), "\n"))
cat(paste0("log_mu = ", log_mu, " D = ", D, " a = ", a, "\n"))

fit_base <- sampling(base_model, data = data)
fit_base   
get_elapsed_time(fit_base)

data$method = 1
fit_base_my <- sampling(base_model, data = data)
fit_base_my
get_elapsed_time(fit_base_my)
```



